import Head from "next/head";

import Transfer from "pages-lib/Transfer";
import TokensProvider from "context/TokensProvider";
import UserInputsProvider from "context/UserInputsProvider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TokensProvider>
        <UserInputsProvider>
          <Transfer />
        </UserInputsProvider>
      </TokensProvider>
    </>
  );
}
